In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,root_mean_squared_error, r2_score,mean_absolute_error

In [2]:
df=pd.read_csv(r"C:\Users\lalit\Downloads\archive (3) (1)\advertising.csv")

In [3]:
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [4]:
df.isna().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [5]:
s=StandardScaler()
X=df.drop("Sales",axis=1)
Y=df["Sales"]
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [6]:
X_train_scaled=s.fit_transform(X_train)
X_test_scaled=s.fit_transform(X_test)

In [7]:
lr=LinearRegression()
lr.fit(X_train_scaled,Y_train)

LinearRegression()

In [8]:
pred_Y=lr.predict(X_test_scaled)

In [9]:
print("MSE:", mean_squared_error(Y_test, pred_Y))
print("RMSE:", root_mean_squared_error(Y_test, pred_Y))
print("R2 Score:", r2_score(Y_test, pred_Y))
print("MAE:", mean_absolute_error(Y_test, pred_Y))

MSE: 3.8167354569435203
RMSE: 1.9536467072998436
R2 Score: 0.8764854501314348
MAE: 1.5906161608556943

In [10]:
%pip install statsmodels

Requirement already satisfied: statsmodels in c:\users\lalit\anaconda3\lib\site-packages (0.14.4)
Requirement already satisfied: numpy<3,>=1.22.3 in c:\users\lalit\anaconda3\lib\site-packages (from statsmodels) (2.1.3)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in c:\users\lalit\anaconda3\lib\site-packages (from statsmodels) (1.15.3)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\users\lalit\anaconda3\lib\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy>=0.5.6 in c:\users\lalit\anaconda3\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging>=21.3 in c:\users\lalit\anaconda3\lib\site-packages (from statsmodels) (24.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lalit\anaconda3\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lalit\anaconda3\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lalit\anaconda3\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\lalit\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_data=pd.DataFrame()

In [12]:
vif_data["feature"]=X.columns
vif_data["VIF"]=[variance_inflation_factor(X.values,i)for i in range(len(X.columns))]
print(vif_data)

     feature       VIF
0         TV  2.486772
1      Radio  3.285462
2  Newspaper  3.055245

In [13]:
X["dummy"]=2*X["TV"]
print(X["dummy"])
print(X.columns)

0      460.2
1       89.0
2       34.4
3      303.0
4      361.6
       ...
195     76.4
196    188.4
197    354.0
198    567.2
199    464.2
Name: dummy, Length: 200, dtype: float64
Index(['TV', 'Radio', 'Newspaper', 'dummy'], dtype='object')

In [14]:
from sklearn.preprocessing import PolynomialFeatures

X=df.drop(columns="Sales",axis=1)
Y=df["Sales"]

poly=PolynomialFeatures(degree=3)
poly_X=poly.fit_transform(X)

X_train,X_test,Y_train,Y_test=train_test_split(poly_X,Y,test_size=0.2,random_state=42)

X_train_scaled=s.fit_transform(X_train)
X_test_scaled=s.fit_transform(X_test)

lr=LinearRegression()
lr.fit(X_train_scaled,Y_train)

LinearRegression()

In [15]:
pred_Y=lr.predict(X_test_scaled)

In [16]:
print("MSE:", mean_squared_error(Y_test, pred_Y))
print("RMSE:", root_mean_squared_error(Y_test, pred_Y))
print("R2 Score:", r2_score(Y_test, pred_Y))
print("MAE:", mean_absolute_error(Y_test, pred_Y))

MSE: 2.7496115691480703
RMSE: 1.6581952747333681
R2 Score: 0.9110189744330114
MAE: 1.3313209149311267

In [17]:
vif_data["feature"]=X.columns
vif_data["VIF"]=[variance_inflation_factor(X.values,i)for i in range(len(X.columns))]
print(vif_data)

     feature       VIF
0         TV  2.486772
1      Radio  3.285462
2  Newspaper  3.055245

In [18]:
poly_X_df=pd.DataFrame(poly_X)
poly_X_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1.0,230.1,37.8,69.2,52946.01,8697.78,15922.92,1428.84,2615.76,4788.64,1.218288e+07,2001359.178,3663863.892,328776.084,601886.376,1101866.064,54010.152,98875.728,181010.592,331373.888
1,1.0,44.5,39.3,45.1,1980.25,1748.85,2006.95,1544.49,1772.43,2034.01,8.812112e+04,77823.825,89309.275,68729.805,78873.135,90513.445,60698.457,69656.499,79936.593,91733.851
2,1.0,17.2,45.9,69.3,295.84,789.48,1191.96,2106.81,3180.87,4802.49,5.088448e+03,13579.056,20501.712,36237.132,54710.964,82602.828,96702.579,146001.933,220434.291,332812.557
3,1.0,151.5,41.3,58.5,22952.25,6256.95,8862.75,1705.69,2416.05,3422.25,3.477266e+06,947927.925,1342706.625,258412.035,366031.575,518470.875,70444.997,99782.865,141338.925,200201.625
4,1.0,180.8,10.8,58.4,32688.64,1952.64,10558.72,116.64,630.72,3410.56,5.910106e+06,353037.312,1909016.576,21088.512,114034.176,616629.248,1259.712,6811.776,36834.048,199176.704